all_clues:
  - head
  - shoulder
  - hip
  - foot

used_segs:
  # - "433"

force_rerun: False
use_space: True
replace_df: False

analysis:
  spatial: False
  temporal: False
  cross_modal: True

plots:
  panels: False

params:
  stride: 40.0
  mdl: 6000.0

paths:
  kp: ../data/export/data.pkl
  kp_finished: ../data/export/data_finished.pkl
  sp: ../data/export/sp_merged.pkl
  frames: ../data/export/frames/
  panel_plots: ../data/results/panel_plots/
  log: ./experiments/logs/
